# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Thống kê
tagline:          Thư viện thống kê
url:              http://thongke.github.io
paginate:         1
baseurl:          /
author:
  name:           YTCC
  url:            http://stats.ytecongcong.com/
  email:          admin@ytecongcong.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/thongke/thongke.github.io

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
